# Generated by Django 4.0.6 on 2022-07-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='api.genre'),
        ),
    ]
