# Generated by Django 4.0.6 on 2022-07-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ebook_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='review',
            field=models.IntegerField(),
        ),
    ]
