# Generated by Django 4.0.6 on 2022-07-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_ebook_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generlst', to='api.genremodel'),
        ),
    ]
