# Generated by Django 4.0.6 on 2022-07-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ebook_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='course',
            new_name='genre',
        ),
    ]
