# Generated by Django 4.0.6 on 2022-07-07 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_course_ebook_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_title', to='api.genremodel'),
        ),
    ]
